    <script src="https://cdn.tailwindcss.com">

console.log('Dashboard JS loading...');
const stateCache={};let ceoTradeVisibleCount=10;let ceoTradeRows=[];let ceoTradeFilter='all';
function filterCeoTrades(rows){if(ceoTradeFilter==='all')return rows;const now=new Date();const st=new Date(now.getFullYear(),now.getMonth(),now.getDate());const dMs=864e5;return rows.filter(t=>{if(!t.exit_time_iso)return false;const d=new Date(t.exit_time_iso);if(isNaN(d))return false;if(ceoTradeFilter==='today')return d>=st;if(ceoTradeFilter==='7d')return(now-d)<=7*dMs;if(ceoTradeFilter==='30d')return(now-d)<=30*dMs;return true})}
function updateCeoFilterButtons(){document.querySelectorAll('#ceo-trades-filters button[data-filter]').forEach(b=>{const a=b.dataset.filter===ceoTradeFilter;b.style.borderColor=a?'var(--accent)':'var(--border)';b.style.color=a?'var(--accent)':'';b.className='px-2 py-1 text-xs rounded border'+(a?'':' text-gray-400')})}
function updateValue(id,v,cls){const el=document.getElementById(id);if(!el)return;if(stateCache[id]!==v){el.innerText=v;if(cls)el.className=cls;const oN=parseFloat((stateCache[id]||'').toString().replace(/[^0-9.\\-]+/g,''));const nN=parseFloat(String(v).replace(/[^0-9.\\-]+/g,''));if(!isNaN(oN)&&!isNaN(nN)&&oN!==nN){el.classList.remove('value-up','value-down');void el.offsetWidth;el.classList.add(nN>oN?'value-up':'value-down')}stateCache[id]=v}}
function rsiC(v){return v>=70?'var(--negative)':v<=30?'var(--positive)':'var(--accent)'}
function tB(t){return t==='bullish'?'<span style="color:var(--positive);font-weight:600">B</span>':t==='bearish'?'<span style="color:var(--negative);font-weight:600">S</span>':'<span style="color:var(--text-secondary)">N</span>'}
function sB(i){if(i.has_position)return'<span class="badge badge-active">● ACTIVA</span>';if(i.can_enter)return'<span class="badge badge-buy">▲ COMPRAR</span>';return'<span class="badge badge-hold">● ESPERAR</span>'}
function renderVibe(v){const b=document.getElementById('vibe-status-badge');if(v.mcp_available){b.className='badge badge-vibe';b.textContent='Conectado'}else{b.className='badge badge-wait';b.textContent='Desconectado'}const d=document.getElementById('dot-vibe');if(d)d.style.color=v.mcp_available?'var(--vibe)':'var(--text-dim)';const c=document.getElementById('vibe-content');let h='';const p=v.patterns||{};const pk=Object.keys(p);if(pk.length){for(const s of pk){const t=p[s]||'';h+=`<div class="vibe-item"><span class="mono text-xs" style="color:var(--vibe);font-weight:600">${s}</span> <span class="text-sm text-gray-300">${t.substring(0,150)}</span></div>`}}else{h+='<div class="text-gray-500 text-sm">🔍 Patrones: esperando datos…</div>'}const j=v.journal||'';if(j){h+=`<div class="vibe-item"><span class="text-xs" style="color:var(--vibe);font-weight:600">📋 Journal</span> <span class="text-sm text-gray-300">${j.substring(0,150)}</span></div>`}else{h+='<div class="text-gray-500 text-sm">📋 Journal: sin analizar</div>'}const bt=v.backtest||{};const bk=Object.keys(bt);if(bk.length){for(const s of bk){const t=bt[s]||'';h+=`<div class="vibe-item"><span class="text-xs" style="color:var(--vibe);font-weight:600">📊 Backtest ${s}</span> <span class="text-sm text-gray-300">${t.substring(0,150)}</span></div>`}}else{h+='<div class="text-gray-500 text-sm">📊 Backtest: semanal…</div>'}const f=v.factors||{};const fk=Object.keys(f);if(fk.length){for(const s of fk){const t=f[s]||'';h+=`<div class="vibe-item"><span class="text-xs" style="color:var(--vibe);font-weight:600">🧬 Factors ${s}</span> <span class="text-sm text-gray-300">${t.substring(0,150)}</span></div>`}}else{h+='<div class="text-gray-500 text-sm">🧬 Factors: mensual…</div>'}const sh=v.shadow||'';if(sh){h+=`<div class="vibe-item"><span class="text-xs" style="color:var(--vibe);font-weight:600">🌙 Shadow</span> <span class="text-sm text-gray-300">${sh.substring(0,150)}</span></div>`}else{h+='<div class="text-gray-500 text-sm">🌙 Shadow: semanal…</div>'}c.innerHTML=h}
async function fetchState(){try{const r=await fetch('/api/state');if(!r.ok){console.error('API error:',r.status);return}const d=await r.json();window.__lastData=d;render(d)}catch(e){console.error('Error fetching state:',e)}}
function render(data){document.getElementById('uptime').innerText=data.uptime;const pair=data.primary_pair||(Array.isArray(data.watchlist)&&data.watchlist[0])||'—';document.getElementById('sentiment').innerText=pair.replace('/',' / ');document.getElementById('sentiment-detail').innerText=data.strategy_blurb||'';const bs=document.getElementById('bot-status');if(data.global_hold){bs.innerHTML='<span style="color:var(--negative)">⛔ Pausa</span>'}else if(data.open_count>0){bs.innerHTML='<span style="color:var(--accent)">⚡ Operando</span>'}else{bs.innerHTML='<span style="color:var(--positive)">✅ Listo</span>'}
updateValue('pos-count',`${data.open_count||0}/${data.max_positions||3}`);updateValue('s-wins',data.session_wins||0);updateValue('s-losses',data.session_losses||0);updateValue('s-winrate',data.session_winrate||'0%');
const th=Number.isFinite(data.buy_prob_threshold_pct)?data.buy_prob_threshold_pct:70;updateValue('sent-num',th+'%');const sb=document.getElementById('sent-bar');if(sb)sb.style.width=Math.min(100,Math.max(0,th))+'%';
const la=document.getElementById('api-latency');if(la){const ms=Number(data.api_latency_ms||0);la.innerText=ms>0?(Math.round(ms)+' ms'):'—'}
updateValue('balance',data.balance);updateValue('balance-lg',data.balance);updateValue('margin',data.available_margin);
const pnlEl=document.getElementById('session-pnl');updateValue('session-pnl',data.session_pnl);if(pnlEl)pnlEl.style.color=data.session_pnl_num>=0?'var(--positive)':'var(--negative)';
const ddEl=document.getElementById('drawdown');updateValue('drawdown',data.max_drawdown);if(ddEl)ddEl.style.color=data.max_drawdown_num<0?'var(--negative)':'var(--text-primary)';
const buyTh=Number.isFinite(data.buy_prob_threshold_pct)?data.buy_prob_threshold_pct:70;
        let rh='';data.market.forEach(i=>{const ml=Math.min(100,Math.max(0,parseFloat(String(i.ml_conf).replace(/[%\\s]/g,''))||0)));const mc=ml>=buyTh?'var(--positive)':'var(--accent)';const rn=(i.rsi==='--'||i.rsi===undefined)?NaN:parseFloat(i.rsi);const rs=Number.isFinite(rn)?rn.toFixed(0):'—';const rv=Number.isFinite(rn)?Math.min(100,Math.max(0,rn)):0;const cc=i.change_ok===true;const chC=!cc?'color:var(--text-dim)':(i.change_num>=0?'color:var(--positive)':'color:var(--negative)');const chG=!cc?'•':(i.change_num>=0?'↗':'↘');const st=i.symbol_pair?String(i.symbol_pair).replace('/',' / '):i.symbol;const rb=i.has_position?'background:rgba(0,212,255,.04)':'';let ph='<span style="color:var(--text-dim)">—</span>';if(i.has_position&&i.unrealized_pnl_num!==undefined){const c=i.unrealized_pnl_num>=0?'var(--positive)':'var(--negative)';ph=`<span class="mono font-medium" style="${c}">${i.unrealized_pnl_num>=0?'+':''}${i.unrealized_pnl_num.toFixed(2)}</span>`}
rh+=`<tr class="mkt-row border-b" style="border-color:var(--border);${rb}"><td class="px-4 py-3"><span class="font-semibold text-white">${st}</span><div class="text-[10px] text-gray-500 mono">${i.symbol}</div></td><td class="px-4 py-3 text-right mono font-medium text-white">${i.price}</td><td class="px-4 py-3 text-right hide-mobile" style="${chC}">${chG} ${i.change}</td><td class="px-4 py-3 text-center hide-mobile"><span class="mono" style="color:${rsiC(Number.isFinite(rn)?rn:50)}">${rs}</span><div class="bar-track mt-1"><div class="bar-fill" style="width:${rv}%;background:${rsiC(Number.isFinite(rn)?rn:50)}"></div></div></td><td class="px-4 py-3 text-center"><span class="mono" style="color:${mc}">${i.ml_conf}</span><div class="bar-track mt-1"><div class="bar-fill" style="width:${ml}%;background:${mc}"></div></div></td><td class="px-4 py-3 text-center hide-mobile">${tB(i.trend_detail?.['15m']||'neutral')}/${tB(i.trend_detail?.['1h']||'neutral')}/${tB(i.trend_detail?.['4h']||'neutral')}</td><td class="px-4 py-3 text-center">${ph}</td><td class="px-4 py-3 text-center">${sB(i)}</td></tr>`});document.getElementById('market-tbody').innerHTML=rh;
        let ph2='';let hp=false;data.market.forEach(i=>{if(!i.has_position)return;hp=true;const pc=i.unrealized_pnl_num>=0?'var(--positive)':'var(--negative)';ph2+=`<tr class="border-b" style="border-color:var(--border)"><td class="px-4 py-2 font-semibold text-white">${i.symbol_pair||i.symbol}</td><td class="px-4 py-2 text-right mono">${i.position_str||'—'}</td><td class="px-4 py-2 text-right mono text-white">${i.price}</td><td class="px-4 py-2 text-right mono" style="color:var(--warning)">${i.stop_loss||'—'}</td><td class="px-4 py-2 text-right mono" style="color:var(--positive)">${i.take_profit||'—'}</td><td class="px-4 py-2 text-right mono font-medium" style="${pc}">${i.unrealized_pnl||'—'}</td><td class="px-4 py-2 text-center">${i.trailing_active?'<span class="badge badge-buy" style="font-size:10px">🔒 TRAIL</span>':'<span class="text-gray-500 text-xs">OFF</span>'}</td></tr>`});document.getElementById('pos-tbody').innerHTML=ph2||'<tr><td colspan="7" class="text-center text-gray-500 py-4">Sin posiciones</td></tr>';document.getElementById('positions-section').classList.toggle('hidden',!hp);
renderVibe(data.vibe||{});
const ceo=data.ceo||{};const ms=v=>v>=0?'color:var(--positive);font-weight:500':'color:var(--negative);font-weight:500';const p7n=Number(ceo.pnl_7d_num||0);const p30n=Number(ceo.pnl_30d_num||0);updateValue('ceo-pnl-7d',ceo.pnl_7d||'—');const p7e=document.getElementById('ceo-pnl-7d');if(p7e)p7e.style.cssText=ms(p7n);updateValue('ceo-winrate-7d',ceo.winrate_7d||'—');updateValue('ceo-pf-30d',ceo.profit_factor_30d||'—');updateValue('ceo-pnl-30d',ceo.pnl_30d||'—');const p30e=document.getElementById('ceo-pnl-30d');if(p30e)p30e.style.cssText=ms(p30n);document.getElementById('ceo-updated').innerText=`Actualizado: ${ceo.last_updated_local||'—'}`;
const syEl=document.getElementById('ceo-symbols');const sy=ceo.symbols_month||[];syEl.innerHTML=sy.length===0?'<div class="text-gray-500">Sin datos</div>':sy.slice(0,6).map(s=>`<div class="flex justify-between"><span class="text-gray-300">${s.symbol}</span><span class="mono" style="${Number(s.pnl_total)>=0?'color:var(--positive)':'color:var(--negative)'}">${s.pnl_label}</span></div>`).join('');
const trEl=document.getElementById('ceo-trades');const tr=ceo.recent_trades||[];ceoTradeRows=tr;const ft=filterCeoTrades(ceoTradeRows);const rc=Math.min(ceoTradeVisibleCount,ft.length);trEl.innerHTML=ft.length===0?'<div class="text-gray-500">Sin trades cerrados</div>':ft.slice(0,rc).map(t=>`<div class="flex justify-between"><span class="text-gray-300">${t.symbol} <span class="text-gray-500">(${t.exit_time_local})</span></span><span class="mono" style="${Number(t.pnl_num)>=0?'color:var(--positive)':'color:var(--negative)'}">${t.pnl}</span></div>`).join('');updateCeoFilterButtons();const mb=document.getElementById('ceo-trades-more');mb.classList.toggle('hidden',ft.length<=rc);mb.innerText=`Cargar más (${ft.length-rc})`;
        const evEl=document.getElementById('events-log');if(data.events.length>0){evEl.innerHTML=data.events.map((e,i)=>`<div class="flex items-start gap-3 py-1.5"><div class="w-1.5 h-1.5 rounded-full mt-1.5 flex-shrink-0" style="background:${i===0?'var(--accent)':'var(--text-dim)'}"></div><div class="text-sm text-gray-300">${e}</div></div>`).join('')}else{evEl.innerHTML='<div class="text-gray-500 text-sm">Sin eventos recientes…</div>'}}
fetchState();setInterval(fetchState,2500);
document.getElementById('ceo-trades-more').addEventListener('click',()=>{
  ceoTradeVisibleCount+=20;
  render({...window.__lastData,ceo:{...(window.__lastData?.ceo||{}),recent_trades:ceoTradeRows}})
});
document.querySelectorAll('#ceo-trades-filters button[data-filter]').forEach(b=>{
  b.addEventListener('click',()=>{
    ceoTradeFilter=b.dataset.filter||'all';
    ceoTradeVisibleCount=10;
    render({...window.__lastData,ceo:{...(window.__lastData?.ceo||{}),recent_trades:ceoTradeRows}})
  })
});
    